### PR TITLE
Include `table_name` in scopes to allow for JOIN operations

### PR DESCRIPTION
**Pull request by fjaeger**

### CODE REVIEW

**Comment by kenn** [comment]
If we want to support general composability, wouldn't we want to quote names?

For instance:

```ruby
connection.quote_table_name_for_assignment(table_name, column_name)
```

**Comment by dmitry** [comment]
What is necessary to finish with this issue?

**Comment by fjaeger** [comment]
I can apply @kenn 's suggestion, if that is generally agreed upon…

**Comment by dmitry** [comment]
@fjaeger I think that will be enough. Another solution to use arel, like: 

```ruby
Arel::Nodes::BitwiseAnd.new(arel_table[attribute], flags.to_i(value)).gt(0)
```

**Comment by kenn** [comment]
I would also add a test case with a composed join operation?

**Comment by fjaeger** [comment]
I applied a refactoring and added a corresponding test

**Comment by kenn** [comment]
Looks like some tests are failing? Would you take a look?

**Comment by fjaeger** [comment]
@kenn I doubt that the failing tests are due to this PR's changes. It seems there was a recent release of https://github.com/sparklemotion/sqlite3-ruby which is only used for Ruby3 and which fails to load on the test environment you are using here.

**Comment by kenn** [comment]
Released as v2.0.0 — thank you, @fjaeger ! 🎉

https://rubygems.org/gems/active_flag

**Pull request merged**
